---
# ensure the role can be included as a meta dependency without ill consequence
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
# simples example of usage
- hosts: all
  vars:
    hashi_apps:
      - name: consul-template
        ver: 0.25.2
      - name: consul
        ver: 1.9.4
      - name: vault
        ver: 1.7.0
  roles:
  - role: '{{ playbook_dir }}'
# examples with meta
- hosts: all
  vars:
    hashi_apps:
      - name: consul
        ver: 1.9.4
        meta: ent
      - name: vault
        ver: 1.7.0
        meta: ent
  roles:
  - role: '{{ playbook_dir }}'
- hosts: all
  vars:
    hashi_apps:
      - name: consul
        ver: 1.9.4
        meta: ''
      - name: vault
        ver: 1.7.0
        meta: ''
  roles:
  - role: '{{ playbook_dir }}'
