---
# ensure the role can be included as a meta dependency without ill consequence
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
    hashi_apps:
      - name: consul
        ver: 1.8.0
      - name: consul-template
        ver: 0.25.0
      - name: vault
        ver: 1.4.2
