---
# ensure the role can be included as a meta dependency without ill consequence
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
# simples example of usage
- hosts: all
  vars:
    hashi_apps:
      - name: consul-template
        ver: 0.35.0
      - name: consul
        ver: 1.17.0
      - name: vault
        ver: 1.15.2
  roles:
    - role: '{{ playbook_dir }}'
# examples with meta
- hosts: all
  vars:
    hashi_apps:
      - name: consul
        ver: 1.17.0
        meta: ent
      - name: vault
        ver: 1.15.2
        meta: ent
  roles:
    - role: '{{ playbook_dir }}'
- hosts: all
  vars:
    hashi_apps:
      - name: consul
        ver: 1.17.0
        meta: ''
      - name: vault
        ver: 1.15.2
        meta: ''
  roles:
    - role: '{{ playbook_dir }}'
